import os

VariantDir('build', 'src')

env = Environment(CCFLAGS = '-Wall -ffast-math -fPIC ',)

DEBUG = int(ARGUMENTS.get('DEBUG', '0'))
if DEBUG:
	CCFLAGS = '-ggdb2 -O0 -DDEBUG=1 '
else:
	CCFLAGS = '-g0 -O3 '
env.Append(CCFLAGS = CCFLAGS)

env.Append(LIBS = ['OpenNI2', 'GL', 'GLU', 'glut',
                   'opencv_core', 'opencv_imgproc', 'opencv_video',
				   'oscpack'])

env.Program(
    target='Tracker',
    source=['build/Tracker.cpp'])
