env = Environment()

env['APP_TARGET'] = 'AIInput'
env['APP_SOURCES'] = ['AIInput.cpp']
env['DEBUG'] = 1

env = SConscript('../../../../blocks/MndlKit/scons/SConscript', exports = 'env')
env = SConscript('../../../../blocks/Cinder-NI/scons/SConscript', exports = 'env')
env = SConscript('../../../../blocks/Cinder-Osc/scons/SConscript', exports = 'env')

SConscript('../../../../scons/SConscript', exports = 'env')

