env = Environment()

env['APP_TARGET'] = 'AIamCaptureTest'
env['APP_SOURCES'] = ['AIamCaptureTest.cpp']
env['ASSETS'] = ['motions/*.bvh']
env['DEBUG'] = 1

env = SConscript('../../../../blocks/Cinder-Assimp/scons/SConscript', exports = 'env')
SConscript('../../../../scons/SConscript', exports = 'env')

